#* In this file, we configure the ros_gz_bridge to enable communication between ROS 2 and Gazebo Classic.
# The bridge allows for the exchange of messages between the two systems, facilitating integration and interoperability.
# The configuration specifies the topics to be bridged, their types, and the direction of communication.

---
# LiDAR data
- ros_topic_name: '/lidar'  
  gz_topic_name:  '/scan'
  ros_type_name: 'sensor_msgs/msg/LaserScan'
  gz_type_name: 'gz.msgs.LaserScan'
  direction: 'GZ_TO_ROS'

# Simulation clock 
- ros_topic_name: '/clock'
  gz_topic_name:  '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: 'GZ_TO_ROS'

# Odometry data (from gazebo)
- ros_topic_name: "/odom"
  gz_topic_name: "/model/robot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# Joint states (from gazebo)
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/car_world/model/robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

  # Camera image (from gazebo)
- ros_topic_name: "/camera"
  gz_topic_name: "/world/car_world/model/robot/link/camera_link/sensor/camera_front/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# TF data (from gazebo)
- ros_topic_name: "/tf"
  gz_topic_name: "/model/robot/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/robot/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

